Repository OCA/stock-logistics-availability, pull requests merged in 2025-01, with the labels that each got.

#24 [17.0] [MIG] stock_available_mrp: Migration to 17.0
  stock_available_mrp/README.rst
  stock_available_mrp/__init__.py
  stock_available_mrp/__manifest__.py
  stock_available_mrp/data/ir_config_parameter.xml
  stock_available_mrp/demo/mrp_data.xml
  stock_available_mrp/i18n/ca.po
  stock_available_mrp/i18n/de.po
  stock_available_mrp/i18n/es.po
  stock_available_mrp/i18n/fi.po
  stock_available_mrp/i18n/fr.po
  stock_available_mrp/i18n/hr_HR.po
  stock_available_mrp/i18n/it.po
  stock_available_mrp/i18n/pt_BR.po
  stock_available_mrp/i18n/sl.po
  stock_available_mrp/i18n/stock_available_mrp.pot
  stock_available_mrp/i18n/zh_CN.po
  stock_available_mrp/migrations/17.0.1.0.0/pre-migration.py
  stock_available_mrp/models/__init__.py
  stock_available_mrp/models/product_product.py
  stock_available_mrp/models/res_config_settings.py
  stock_available_mrp/pyproject.toml
  stock_available_mrp/readme/CONTRIBUTORS.md
  stock_available_mrp/readme/DESCRIPTION.md
  stock_available_mrp/readme/ROADMAP.md
  stock_available_mrp/static/description/icon.png
  stock_available_mrp/static/description/index.html
  stock_available_mrp/tests/__init__.py
  stock_available_mrp/tests/test_potential_qty.py
  stock_available_mrp/views/res_config_settings_views.xml
Labels: needs review, approved, migration, bot is merging ⏳

#35 [17.0][FW][FIX] stock_available_mrp: variant BoMs #17
  stock_available_mrp/models/product_product.py
  stock_available_mrp/tests/test_potential_qty.py
Labels: bot is merging ⏳

#36 [17.0][MIG] stock_available_immediately: Migration to version 17.0
  stock_available_immediately/README.rst
  stock_available_immediately/__init__.py
  stock_available_immediately/__manifest__.py
  stock_available_immediately/i18n/ca.po
  stock_available_immediately/i18n/cs_CZ.po
  stock_available_immediately/i18n/de.po
  stock_available_immediately/i18n/el_GR.po
  stock_available_immediately/i18n/es.po
  stock_available_immediately/i18n/es_ES.po
  stock_available_immediately/i18n/es_MX.po
  stock_available_immediately/i18n/eu.po
  stock_available_immediately/i18n/fi.po
  stock_available_immediately/i18n/fr.po
  stock_available_immediately/i18n/fr_CH.po
  stock_available_immediately/i18n/fr_FR.po
  stock_available_immediately/i18n/gl.po
  stock_available_immediately/i18n/hr.po
  stock_available_immediately/i18n/hr_HR.po
  stock_available_immediately/i18n/it.po
  stock_available_immediately/i18n/nl.po
  stock_available_immediately/i18n/nl_NL.po
  stock_available_immediately/i18n/pt.po
  stock_available_immediately/i18n/pt_BR.po
  stock_available_immediately/i18n/ro.po
  stock_available_immediately/i18n/ru.po
  stock_available_immediately/i18n/sl.po
  stock_available_immediately/i18n/stock_available_immediately.pot
  stock_available_immediately/i18n/tr.po
  stock_available_immediately/i18n/tr_TR.po
  stock_available_immediately/i18n/vi_VN.po
  stock_available_immediately/i18n/zh_CN.po
  stock_available_immediately/models/__init__.py
  stock_available_immediately/models/product_product.py
  stock_available_immediately/pyproject.toml
  stock_available_immediately/readme/CONTRIBUTORS.md
  stock_available_immediately/readme/DESCRIPTION.md
  stock_available_immediately/static/description/icon.png
  stock_available_immediately/static/description/index.html
  stock_available_immediately/tests/__init__.py
  stock_available_immediately/tests/test_stock_available_immediately.py
Labels: bot is merging ⏳

#34 [16.0][MIG] stock_available_exclude_location
  setup/stock_available_exclude_location/odoo/addons/stock_available_exclude_location
  setup/stock_available_exclude_location/setup.py
  stock_available_exclude_location/README.rst
  stock_available_exclude_location/__init__.py
  stock_available_exclude_location/__manifest__.py
  stock_available_exclude_location/models/__init__.py
  stock_available_exclude_location/models/product_product.py
  stock_available_exclude_location/models/res_company.py
  stock_available_exclude_location/models/res_config_settings.py
  stock_available_exclude_location/readme/CONFIGURE.rst
  stock_available_exclude_location/readme/CONTRIBUTORS.rst
  stock_available_exclude_location/readme/DESCRIPTION.rst
  stock_available_exclude_location/static/description/icon.png
  stock_available_exclude_location/static/description/index.html
  stock_available_exclude_location/tests/__init__.py
  stock_available_exclude_location/tests/test_exclude_location.py
  stock_available_exclude_location/views/res_config_settings.xml
Labels: approved, ready to merge, bot is merging ⏳
