Repository OCA/stock-logistics-availability, pull requests merged in 2025-06, with the labels that each got.

#40 [18.0][MIG] stock_available_unreserved: Migration to 18.0
  stock_available_unreserved/README.rst
  stock_available_unreserved/__init__.py
  stock_available_unreserved/__manifest__.py
  stock_available_unreserved/i18n/ar.po
  stock_available_unreserved/i18n/ca.po
  stock_available_unreserved/i18n/de.po
  stock_available_unreserved/i18n/el_GR.po
  stock_available_unreserved/i18n/es.po
  stock_available_unreserved/i18n/es_ES.po
  stock_available_unreserved/i18n/es_MX.po
  stock_available_unreserved/i18n/eu.po
  stock_available_unreserved/i18n/fi.po
  stock_available_unreserved/i18n/fr.po
  stock_available_unreserved/i18n/fr_CH.po
  stock_available_unreserved/i18n/fr_FR.po
  stock_available_unreserved/i18n/gl.po
  stock_available_unreserved/i18n/hr.po
  stock_available_unreserved/i18n/hr_HR.po
  stock_available_unreserved/i18n/it.po
  stock_available_unreserved/i18n/nl.po
  stock_available_unreserved/i18n/nl_NL.po
  stock_available_unreserved/i18n/pt.po
  stock_available_unreserved/i18n/pt_BR.po
  stock_available_unreserved/i18n/ro.po
  stock_available_unreserved/i18n/ru.po
  stock_available_unreserved/i18n/sl.po
  stock_available_unreserved/i18n/stock_available_unreserved.pot
  stock_available_unreserved/i18n/tr.po
  stock_available_unreserved/i18n/tr_TR.po
  stock_available_unreserved/i18n/vi_VN.po
  stock_available_unreserved/i18n/zh_CN.po
  stock_available_unreserved/models/__init__.py
  stock_available_unreserved/models/product_product.py
  stock_available_unreserved/models/product_template.py
  stock_available_unreserved/models/stock_quant.py
  stock_available_unreserved/pyproject.toml
  stock_available_unreserved/readme/CONTRIBUTORS.md
  stock_available_unreserved/readme/DESCRIPTION.md
  stock_available_unreserved/static/description/icon.png
  stock_available_unreserved/static/description/index.html
  stock_available_unreserved/tests/__init__.py
  stock_available_unreserved/tests/test_stock_available_unreserved.py
  stock_available_unreserved/views/product_view.xml
  stock_available_unreserved/views/stock_quant_view.xml
Labels: approved, bot is merging ⏳

#51 [18.0][MIG] stock_available_base_exclude_location: Migration to 18.0
  requirements.txt
  stock_available_base_exclude_location/README.rst
  stock_available_base_exclude_location/__init__.py
  stock_available_base_exclude_location/__manifest__.py
  stock_available_base_exclude_location/i18n/it.po
  stock_available_base_exclude_location/i18n/stock_available_base_exclude_location.pot
  stock_available_base_exclude_location/models/__init__.py
  stock_available_base_exclude_location/models/product_product.py
  stock_available_base_exclude_location/models/stock_exclude_location_mixin.py
  stock_available_base_exclude_location/pyproject.toml
  stock_available_base_exclude_location/readme/CONTRIBUTORS.md
  stock_available_base_exclude_location/readme/DESCRIPTION.md
  stock_available_base_exclude_location/readme/USAGE.md
  stock_available_base_exclude_location/static/description/icon.png
  stock_available_base_exclude_location/static/description/index.html
  stock_available_base_exclude_location/tests/__init__.py
  stock_available_base_exclude_location/tests/common.py
  stock_available_base_exclude_location/tests/test_stock_exclude_location.py
Labels: merged 🎉

#56 [18.0] [MIG] stock_available_immediately: Migration to 18.0
  stock_available_immediately/README.rst
  stock_available_immediately/__init__.py
  stock_available_immediately/__manifest__.py
  stock_available_immediately/i18n/ca.po
  stock_available_immediately/i18n/cs_CZ.po
  stock_available_immediately/i18n/de.po
  stock_available_immediately/i18n/el_GR.po
  stock_available_immediately/i18n/es.po
  stock_available_immediately/i18n/es_ES.po
  stock_available_immediately/i18n/es_MX.po
  stock_available_immediately/i18n/eu.po
  stock_available_immediately/i18n/fi.po
  stock_available_immediately/i18n/fr.po
  stock_available_immediately/i18n/fr_CH.po
  stock_available_immediately/i18n/fr_FR.po
  stock_available_immediately/i18n/gl.po
  stock_available_immediately/i18n/hr.po
  stock_available_immediately/i18n/hr_HR.po
  stock_available_immediately/i18n/it.po
  stock_available_immediately/i18n/nl.po
  stock_available_immediately/i18n/nl_NL.po
  stock_available_immediately/i18n/pt.po
  stock_available_immediately/i18n/pt_BR.po
  stock_available_immediately/i18n/ro.po
  stock_available_immediately/i18n/ru.po
  stock_available_immediately/i18n/sl.po
  stock_available_immediately/i18n/stock_available_immediately.pot
  stock_available_immediately/i18n/tr.po
  stock_available_immediately/i18n/tr_TR.po
  stock_available_immediately/i18n/vi_VN.po
  stock_available_immediately/i18n/zh_CN.po
  stock_available_immediately/models/__init__.py
  stock_available_immediately/models/product_product.py
  stock_available_immediately/pyproject.toml
  stock_available_immediately/readme/CONTRIBUTORS.md
  stock_available_immediately/readme/DESCRIPTION.md
  stock_available_immediately/static/description/icon.png
  stock_available_immediately/static/description/index.html
  stock_available_immediately/tests/__init__.py
  stock_available_immediately/tests/test_stock_available_immediately.py
Labels: approved, merged 🎉

#58 [18.0] [MIG] stock_available_location_get_domain: Migration to 18.0
  stock_available_location_get_domain/README.rst
  stock_available_location_get_domain/__init__.py
  stock_available_location_get_domain/__manifest__.py
  stock_available_location_get_domain/i18n/it.po
  stock_available_location_get_domain/i18n/stock_available_location_get_domain.pot
  stock_available_location_get_domain/models/__init__.py
  stock_available_location_get_domain/models/product_product.py
  stock_available_location_get_domain/pyproject.toml
  stock_available_location_get_domain/readme/CONTRIBUTORS.md
  stock_available_location_get_domain/readme/DESCRIPTION.md
  stock_available_location_get_domain/readme/USAGE.md
  stock_available_location_get_domain/static/description/icon.png
  stock_available_location_get_domain/static/description/index.html
  stock_available_location_get_domain/tests/__init__.py
  stock_available_location_get_domain/tests/test_location_domain.py
Labels: bot is merging ⏳
